env:
    node: true
    commonjs: true
    es2020: true
extends:
    - 'eslint:recommended'
    - 'plugin:prettier/recommended'
parserOptions:
    ecmaVersion: 2020
    sourceType: 'module'
rules:
    prettier/prettier:
        - 'error'
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
